In [ ]:
# This notebook will pre-process the librivox test-clean dataset, 
#   1) loading the csv, 
#   2) converting it to spectogram format and then
#   3) saving it

In [134]:
import pandas as pd
from soundfile import read
import sys
import numpy
numpy.set_printoptions(threshold=sys.maxsize)

sr = 0
df = pd.read_csv("librivox-test-clean.csv")

def convert_to_spectogram(filename):
    global sr
    spectogram_frames, sr = read(filename)
    return spectogram_frames

df['spectogram'] = df['filename'].apply(convert_to_spectogram)
df['sr'] = sr
df2 = df.filter(["transcript", "spectogram", "sr"])
df2

transcript  \
0     young fitzooth had been commanded to his mothe...   
1     there befell an anxious interview mistress fit...   
2     most of all robin thought of his father what w...   
3     if for a whim you beggar yourself i cannot sta...   
4     but take it whilst i live and wear montfichet'...   
...                                                 ...   
2615  it is evident therefore that the present trend...   
2616  it is also noticeable that the serviceability ...   
2617  consumption becomes a larger element in the st...   
2618  among the country population its place is to s...   
2619  the result is a great mobility of the labor em...   

                                             spectogram     sr  
0     [0.000732421875, 0.000823974609375, 0.00173950...  16000  
1     [-0.007781982421875, -0.00921630859375, -0.009...  16000  
2     [0.0029296875, 0.00299072265625, 0.00280761718...  16000  
3     [0.009063720703125, 0.010284423828125, 0.00955...  16000  
4     [-0.0091552734375, -0.0106201171875, -0.013427...  16000  
...                                                 ...    ...  
2615  [0.002349853515625, 0.002777099609375, 0.00302...  16000  
2616  [-3.0517578125e-05, 0.0, -0.0001220703125, 0.0...  16000  
2617  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  16000  
2618  [0.0042724609375, 0.00457763671875, 0.00469970...  16000  
2619  [0.0030517578125, 0.002899169921875, 0.0032653...  16000  

[2620 rows x 3 columns]

In [137]:
# df2.to_csv('teste.csv')
df2.to_hdf(r'file.h5', key='stage', mode='w')

# np.save('spectogram', df2.to_numpy())

/Users/gabriel.t.nishimura/miniconda3/envs/usp/lib/python3.6/site-packages/pandas/core/generic.py:2505: PerformanceWarning: 
your performance may suffer as PyTables will pickle object types that it cannot
map directly to c-types [inferred_type->mixed,key->block0_values] [items->Index(['transcript', 'spectogram'], dtype='object')]

  encoding=encoding,


OverflowError: value too large to convert to int

In [ ]:
df = pd.read_csv("teste.csv")
df

In [128]:
data = np.load('spectogram.npy', allow_pickle=True)
data

array([["young fitzooth had been commanded to his mother's chamber so soon as he had come out from his converse with the squire",
        array([ 0.00073242,  0.00082397,  0.0017395 , ..., -0.00631714,
       -0.00570679, -0.00668335]),
        16000],
       ["there befell an anxious interview mistress fitzooth arguing for and against the squire's project in a breath",
        array([-0.00778198, -0.00921631, -0.00909424, ..., -0.00262451,
       -0.00671387, -0.01138306]),
        16000],
       ['most of all robin thought of his father what would he counsel',
        array([ 0.00292969,  0.00299072,  0.00280762, ..., -0.00195312,
       -0.00192261, -0.00283813]),
        16000],
       ...,
       ['consumption becomes a larger element in the standard of living in the city than in the country',
        array([0.        , 0.        , 0.        , ..., 0.00424194, 0.00424194,
       0.00466919]),
        16000],
       ['among the country population its place is to some extent taken b